"""Distill the GPU policy into a single portable Lua decision tree."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Mapping

from .train_policy import FEATURES, LABELS, _metrics


DEPTH_CANDIDATES = (6, 8, 10, 12)


def _teacher_predictions(bundle: Mapping[str, Any], transformed: Any) -> Any:
    import numpy as np

    from .train_policy import apply_probability_biases

    raw_probabilities = bundle["model"].predict_proba(transformed)
    aligned = np.zeros((raw_probabilities.shape[0], len(LABELS)), dtype=float)
    for column, raw_class in enumerate(bundle["model"].classes_):
        label_index = int(raw_class) if isinstance(raw_class, (int, np.integer)) else LABELS.index(str(raw_class))
        aligned[:, label_index] = raw_probabilities[:, column]
    indices = apply_probability_biases(aligned, bundle.get("class_biases", [1.0] * len(LABELS)))
    return np.array([LABELS[index] for index in indices])


def render_lua_tree(
    student: Any, preprocessor: Any, hero_internal_names: dict[int, str] | None = None
) -> str:
    """Render a fitted sklearn tree plus preprocessing as a standalone Lua module."""

    import numpy as np
    from sklearn.tree import _tree

    feature_names = list(preprocessor.get_feature_names_out())
    categorical = preprocessor.named_transformers_["categorical"]
    scaler = preprocessor.named_transformers_["numeric"]
    lines = [
        "-- Generated by dota_replay_lab.export_lua_policy. Do not edit by hand.",
        "local M = {}",
        "",
        "local hero_ids = {",
    ]
    for hero_id, internal_name in sorted((hero_internal_names or {}).items()):
        lines.append(f"  [{json.dumps(internal_name)}] = {hero_id},")
    lines.extend(
        [
        "}",
        "",
        "function M.hero_id(unit_name)",
        "  return hero_ids[unit_name] or 0",
        "end",
        "",
        "function M.build_features(state)",
        "  local f = {}",
        ]
    )
    feature_index = 1
    for column, categories in zip(("hero_id", "team"), categorical.categories_):
        for value in categories:
            rendered = json.dumps(value.item() if hasattr(value, "item") else value, ensure_ascii=False)
            lines.append(f"  f[{feature_index}] = state.{column} == {rendered} and 1 or 0")
            feature_index += 1
    for column, mean, scale in zip(preprocessor.transformers_[1][2], scaler.mean_, scaler.scale_):
        safe_scale = float(scale) if float(scale) != 0 else 1.0
        lines.append(
            f"  f[{feature_index}] = ((tonumber(state.{column}) or 0) - {float(mean):.17g}) / {safe_scale:.17g}"
        )
        feature_index += 1
    lines.extend(["  return f", "end", "", "local nodes = {"])

    tree = student.tree_
    for node in range(tree.node_count):
        if tree.feature[node] == _tree.TREE_UNDEFINED:
            class_index = int(np.argmax(tree.value[node][0]))
            label = str(student.classes_[class_index])
            lines.append(f"  [{node + 1}] = {{ label = {json.dumps(label)} }},")
        else:
            lines.append(
                "  [{node}] = {{ feature = {feature}, threshold = {threshold:.17g}, left = {left}, right = {right} }}, -- {name}".format(
                    node=node + 1,
                    feature=int(tree.feature[node]) + 1,
                    threshold=float(tree.threshold[node]),
                    left=int(tree.children_left[node]) + 1,
                    right=int(tree.children_right[node]) + 1,
                    name=feature_names[int(tree.feature[node])],
                )
            )
    lines.extend(
        [
            "}",
            "",
            "function M.predict_features(features)",
            "  local index = 1",
            "  while nodes[index].label == nil do",
            "    local node = nodes[index]",
            "    if features[node.feature] <= node.threshold then",
            "      index = node.left",
            "    else",
            "      index = node.right",
            "    end",
            "  end",
            "  return nodes[index].label",
            "end",
            "",
            "function M.predict(state)",
            "  return M.predict_features(M.build_features(state))",
            "end",
            "",
            "return M",
            "",
        ]
    )
    return "\n".join(lines)


def distill_policy(
    dataset: Path,
    model_path: Path,
    metrics_path: Path,
    manifest_path: Path,
    output: Path,
    seed: int,
) -> dict[str, Any]:
    import joblib
    import numpy as np
    import pandas as pd
    from sklearn.metrics import accuracy_score
    from sklearn.tree import DecisionTreeClassifier

    frame = pd.read_csv(dataset)
    bundle = joblib.load(model_path)
    training_metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
    test_match_ids = set(training_metrics["match_ids"]["test"])
    development = frame[~frame["match_id"].isin(test_match_ids)].copy()
    test = frame[frame["match_id"].isin(test_match_ids)].copy()
    development_ids = sorted(development["match_id"].unique())
    rng = np.random.default_rng(seed)
    rng.shuffle(development_ids)
    fidelity_validation_ids = set(development_ids[: max(1, round(len(development_ids) * 0.2))])
    fit_mask = ~development["match_id"].isin(fidelity_validation_ids)

    development_x = bundle["preprocessor"].transform(development[FEATURES])
    test_x = bundle["preprocessor"].transform(test[FEATURES])
    teacher_development = _teacher_predictions(bundle, development_x)
    teacher_test = _teacher_predictions(bundle, test_x)
    validation_results = {}
    for depth in DEPTH_CANDIDATES:
        student = DecisionTreeClassifier(max_depth=depth, min_samples_leaf=20, random_state=seed)
        student.fit(development_x[fit_mask.to_numpy()], teacher_development[fit_mask.to_numpy()])
        predictions = student.predict(development_x[~fit_mask.to_numpy()])
        validation_results[str(depth)] = float(
            accuracy_score(teacher_development[~fit_mask.to_numpy()], predictions)
        )
    chosen_depth = int(max(validation_results, key=validation_results.get))
    student = DecisionTreeClassifier(max_depth=chosen_depth, min_samples_leaf=20, random_state=seed)
    student.fit(development_x, teacher_development)
    student_test = student.predict(test_x)
    result = {
        "chosen_depth": chosen_depth,
        "node_count": int(student.tree_.node_count),
        "fidelity_validation": validation_results,
        "teacher_fidelity_test": float(accuracy_score(teacher_test, student_test)),
        "student_test": _metrics(test["label"].to_numpy(), student_test),
        "teacher_test": _metrics(test["label"].to_numpy(), teacher_test),
        "test_rows": len(test),
    }
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    hero_internal_names = {
        int(hero_id): str(name) for hero_id, name in manifest.get("hero_internal_names", {}).items()
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        render_lua_tree(student, bundle["preprocessor"], hero_internal_names), encoding="utf-8"
    )
    output.with_suffix(".metrics.json").write_text(json.dumps(result, indent=2), encoding="utf-8")
    return result


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Distill the trained policy into standalone Lua.")
    parser.add_argument("--dataset", type=Path, default=Path("artifacts/datasets/decision-labels-v2.csv"))
    parser.add_argument("--model", type=Path, default=Path("artifacts/models/decision-policy-v1.joblib"))
    parser.add_argument(
        "--metrics", type=Path, default=Path("artifacts/models/decision-policy-v1.metrics.json")
    )
    parser.add_argument("--manifest", type=Path, default=Path("artifacts/corpora/pro-matches-v1.json"))
    parser.add_argument("--output", type=Path, default=Path("bots/decision_policy.lua"))
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    result = distill_policy(args.dataset, args.model, args.metrics, args.manifest, args.output, args.seed)
    print(f"Saved portable policy: {args.output}")
    print(f"Depth: {result['chosen_depth']}; nodes: {result['node_count']}")
    print(f"Teacher fidelity on test: {result['teacher_fidelity_test']:.4f}")
    print(f"Student held-out macro-F1: {result['student_test']['macro_f1']:.4f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
