"""Export the audited runtime combat ensemble to standalone Lua with parity."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

from .replay_behavior import load_trajectory_corpus
from .replay_combat import build_combat_frame


def _number(value: float) -> str:
    if not math.isfinite(value):
        raise ValueError("Combat model contains a non-finite number")
    return format(float(value), ".17g")


def _tree_table(predictor: Any) -> str:
    rows = []
    for node in predictor.nodes:
        if int(node["is_categorical"]):
            raise ValueError("Categorical HistGradientBoosting nodes are not supported")
        rows.append(
            "{%d,%s,%d,%d,%d,%s,%d}"
            % (
                int(node["feature_idx"]) + 1,
                _number(node["num_threshold"]),
                int(node["left"]) + 1,
                int(node["right"]) + 1,
                int(node["is_leaf"]),
                _number(node["value"]),
                int(node["missing_go_to_left"]),
            )
        )
    return "{" + ",".join(rows) + "}"


def combat_bundle_to_lua(bundle: dict[str, Any]) -> str:
    """Serialize two fitted binary HistGradientBoosting models."""

    features = list(bundle["features"])
    labels = list(bundle["labels"])
    models = list(bundle["models"])
    thresholds = bundle["thresholds"]
    if len(labels) != 2 or len(models) != 2:
        raise ValueError("Expected exactly engage and threat combat models")
    lines = [
        "-- Generated by dota_replay_lab.export_combat_lua; do not edit.",
        "local M = {}",
        "local features = {" + ",".join(json.dumps(value) for value in features) + "}",
        "local thresholds = {" + ",".join(_number(value) for value in thresholds) + "}",
        "local baselines = {"
        + ",".join(_number(model._baseline_prediction[0, 0]) for model in models)
        + "}",
        "local forests = {",
    ]
    for model in models:
        lines.append("{")
        for iteration in model._predictors:
            lines.append(_tree_table(iteration[0]) + ",")
        lines.append("},")
    lines.extend(
        [
            "}",
            "local function sigmoid(value)",
            "  if value >= 0 then local z = math.exp(-value); return 1 / (1 + z) end",
            "  local z = math.exp(value); return z / (1 + z)",
            "end",
            "local function tree_value(nodes, values)",
            "  local index = 1",
            "  while true do",
            "    local node = nodes[index]",
            "    if node[5] == 1 then return node[6] end",
            "    local value = values[node[1]]",
            "    if value ~= value then index = node[7] == 1 and node[3] or node[4]",
            "    elseif value <= node[2] then index = node[3] else index = node[4] end",
            "  end",
            "end",
            "function M.predict(state)",
            "  local values = {}",
            "  for index, name in ipairs(features) do values[index] = tonumber(state[name]) or 0 end",
            "  local probabilities = {}",
            "  for output = 1, 2 do",
            "    local raw = baselines[output]",
            "    for _, nodes in ipairs(forests[output]) do raw = raw + tree_value(nodes, values) end",
            "    probabilities[output] = sigmoid(raw)",
            "  end",
            "  return {",
            "    engage_probability = probabilities[1],",
            "    threat_probability = probabilities[2],",
            "    engage = probabilities[1] >= thresholds[1],",
            "    threat = probabilities[2] >= thresholds[2],",
            "  }",
            "end",
            "M.features = features",
            "M.thresholds = thresholds",
            "return M",
            "",
        ]
    )
    return "\n".join(lines)


def export_combat_lua(
    model_path: Path,
    output: Path,
    trajectory_dir: Path,
    *,
    parity_rows: int = 1000,
    horizon: int = 5,
) -> dict[str, Any]:
    """Export a trusted local bundle and compare Lua with sklearn probabilities."""

    import joblib
    import numpy as np
    from lupa import LuaRuntime

    bundle = joblib.load(model_path)
    source = combat_bundle_to_lua(bundle)
    lua = LuaRuntime(unpack_returned_tuples=True)
    module = lua.execute(source)
    raw = load_trajectory_corpus(trajectory_dir.glob("*.seconds.csv"))
    frame = build_combat_frame(raw, horizon=horizon)
    sample = frame.sample(n=min(parity_rows, len(frame)), random_state=42)
    features = list(bundle["features"])
    matrix = np.nan_to_num(sample.loc[:, features].to_numpy(dtype=np.float32))
    expected = np.column_stack(
        [model.predict_proba(matrix)[:, 1] for model in bundle["models"]]
    )
    largest_error = 0.0
    matches = 0
    for row_index, values in enumerate(matrix):
        state = lua.table_from(
            {name: float(values[index]) for index, name in enumerate(features)}
        )
        prediction = module["predict"](state)
        actual = np.array(
            [prediction["engage_probability"], prediction["threat_probability"]]
        )
        largest_error = max(largest_error, float(np.max(np.abs(actual - expected[row_index]))))
        expected_classes = expected[row_index] >= np.asarray(bundle["thresholds"])
        matches += int(
            bool(prediction["engage"]) == bool(expected_classes[0])
            and bool(prediction["threat"]) == bool(expected_classes[1])
        )
    if largest_error > 1e-10 or matches != len(sample):
        raise RuntimeError(
            f"Lua parity failed: max error {largest_error}, class matches {matches}/{len(sample)}"
        )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(source, encoding="utf-8")
    return {
        "source_model": str(model_path),
        "rows": int(len(sample)),
        "class_matches": matches,
        "largest_probability_error": largest_error,
        "lua_bytes": output.stat().st_size,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--model",
        type=Path,
        default=Path("artifacts/replay-combat-models-runtime/replay-combat-v1.joblib"),
    )
    parser.add_argument(
        "--trajectory-dir", type=Path, default=Path("artifacts/replay-combat-trajectories")
    )
    parser.add_argument("--output", type=Path, default=Path("bots/replay_combat_policy.lua"))
    parser.add_argument("--parity-rows", type=int, default=1000)
    parser.add_argument("--horizon", type=int, default=5)
    parser.add_argument(
        "--metrics-source",
        type=Path,
        default=Path("artifacts/replay-combat-models-runtime/replay-combat-v1.metrics.json"),
    )
    parser.add_argument(
        "--metrics-output",
        type=Path,
        default=Path("bots/replay_combat_policy.metrics.json"),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    result = export_combat_lua(
        args.model,
        args.output,
        args.trajectory_dir,
        parity_rows=args.parity_rows,
        horizon=args.horizon,
    )
    if args.metrics_source.exists():
        metrics = json.loads(args.metrics_source.read_text(encoding="utf-8"))
        metrics["lua_parity"] = result
        args.metrics_output.write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    print(
        f"Lua parity {result['class_matches']}/{result['rows']}; "
        f"max probability error {result['largest_probability_error']:.3g}; "
        f"bytes {result['lua_bytes']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
