-- Generated by dota_replay_lab.export_lua_policy. Do not edit by hand.
local M = {}

function M.build_features(state)
  local f = {}
  f[1] = state.hero_id == 2 and 1 or 0
  f[2] = state.hero_id == 3 and 1 or 0
  f[3] = state.hero_id == 5 and 1 or 0
  f[4] = state.hero_id == 7 and 1 or 0
  f[5] = state.hero_id == 9 and 1 or 0
  f[6] = state.hero_id == 10 and 1 or 0
  f[7] = state.hero_id == 11 and 1 or 0
  f[8] = state.hero_id == 13 and 1 or 0
  f[9] = state.hero_id == 14 and 1 or 0
  f[10] = state.hero_id == 15 and 1 or 0
  f[11] = state.hero_id == 16 and 1 or 0
  f[12] = state.hero_id == 17 and 1 or 0
  f[13] = state.hero_id == 18 and 1 or 0
  f[14] = state.hero_id == 19 and 1 or 0
  f[15] = state.hero_id == 20 and 1 or 0
  f[16] = state.hero_id == 21 and 1 or 0
  f[17] = state.hero_id == 22 and 1 or 0
  f[18] = state.hero_id == 23 and 1 or 0
  f[19] = state.hero_id == 25 and 1 or 0
  f[20] = state.hero_id == 26 and 1 or 0
  f[21] = state.hero_id == 27 and 1 or 0
  f[22] = state.hero_id == 28 and 1 or 0
  f[23] = state.hero_id == 29 and 1 or 0
  f[24] = state.hero_id == 30 and 1 or 0
  f[25] = state.hero_id == 31 and 1 or 0
  f[26] = state.hero_id == 33 and 1 or 0
  f[27] = state.hero_id == 34 and 1 or 0
  f[28] = state.hero_id == 36 and 1 or 0
  f[29] = state.hero_id == 38 and 1 or 0
  f[30] = state.hero_id == 40 and 1 or 0
  f[31] = state.hero_id == 43 and 1 or 0
  f[32] = state.hero_id == 45 and 1 or 0
  f[33] = state.hero_id == 46 and 1 or 0
  f[34] = state.hero_id == 47 and 1 or 0
  f[35] = state.hero_id == 48 and 1 or 0
  f[36] = state.hero_id == 51 and 1 or 0
  f[37] = state.hero_id == 53 and 1 or 0
  f[38] = state.hero_id == 54 and 1 or 0
  f[39] = state.hero_id == 55 and 1 or 0
  f[40] = state.hero_id == 56 and 1 or 0
  f[41] = state.hero_id == 57 and 1 or 0
  f[42] = state.hero_id == 58 and 1 or 0
  f[43] = state.hero_id == 60 and 1 or 0
  f[44] = state.hero_id == 61 and 1 or 0
  f[45] = state.hero_id == 64 and 1 or 0
  f[46] = state.hero_id == 65 and 1 or 0
  f[47] = state.hero_id == 67 and 1 or 0
  f[48] = state.hero_id == 68 and 1 or 0
  f[49] = state.hero_id == 69 and 1 or 0
  f[50] = state.hero_id == 70 and 1 or 0
  f[51] = state.hero_id == 71 and 1 or 0
  f[52] = state.hero_id == 72 and 1 or 0
  f[53] = state.hero_id == 73 and 1 or 0
  f[54] = state.hero_id == 74 and 1 or 0
  f[55] = state.hero_id == 75 and 1 or 0
  f[56] = state.hero_id == 76 and 1 or 0
  f[57] = state.hero_id == 77 and 1 or 0
  f[58] = state.hero_id == 78 and 1 or 0
  f[59] = state.hero_id == 79 and 1 or 0
  f[60] = state.hero_id == 80 and 1 or 0
  f[61] = state.hero_id == 83 and 1 or 0
  f[62] = state.hero_id == 85 and 1 or 0
  f[63] = state.hero_id == 86 and 1 or 0
  f[64] = state.hero_id == 87 and 1 or 0
  f[65] = state.hero_id == 88 and 1 or 0
  f[66] = state.hero_id == 89 and 1 or 0
  f[67] = state.hero_id == 90 and 1 or 0
  f[68] = state.hero_id == 91 and 1 or 0
  f[69] = state.hero_id == 96 and 1 or 0
  f[70] = state.hero_id == 97 and 1 or 0
  f[71] = state.hero_id == 98 and 1 or 0
  f[72] = state.hero_id == 99 and 1 or 0
  f[73] = state.hero_id == 100 and 1 or 0
  f[74] = state.hero_id == 101 and 1 or 0
  f[75] = state.hero_id == 103 and 1 or 0
  f[76] = state.hero_id == 105 and 1 or 0
  f[77] = state.hero_id == 106 and 1 or 0
  f[78] = state.hero_id == 107 and 1 or 0
  f[79] = state.hero_id == 108 and 1 or 0
  f[80] = state.hero_id == 109 and 1 or 0
  f[81] = state.hero_id == 110 and 1 or 0
  f[82] = state.hero_id == 111 and 1 or 0
  f[83] = state.hero_id == 112 and 1 or 0
  f[84] = state.hero_id == 114 and 1 or 0
  f[85] = state.hero_id == 119 and 1 or 0
  f[86] = state.hero_id == 120 and 1 or 0
  f[87] = state.hero_id == 121 and 1 or 0
  f[88] = state.hero_id == 123 and 1 or 0
  f[89] = state.hero_id == 126 and 1 or 0
  f[90] = state.hero_id == 128 and 1 or 0
  f[91] = state.hero_id == 131 and 1 or 0
  f[92] = state.hero_id == 135 and 1 or 0
  f[93] = state.hero_id == 136 and 1 or 0
  f[94] = state.hero_id == 137 and 1 or 0
  f[95] = state.hero_id == 145 and 1 or 0
  f[96] = state.hero_id == 155 and 1 or 0
  f[97] = state.team == "Dire" and 1 or 0
  f[98] = state.team == "Radiant" and 1 or 0
  f[99] = ((tonumber(state.state_minute) or 0) - 21.283866057838662) / 13.97309651256611
  f[100] = ((tonumber(state.gold) or 0) - 9494.6243531202435) / 8795.1485025220609
  f[101] = ((tonumber(state.experience) or 0) - 11655.74394977169) / 11550.903032219718
  f[102] = ((tonumber(state.last_hits) or 0) - 129.3630898021309) / 150.17785566861477
  f[103] = ((tonumber(state.gold_change) or 0) - 498.32766362252664) / 351.23412650876327
  f[104] = ((tonumber(state.experience_change) or 0) - 641.10205479452054) / 671.57303862336778
  f[105] = ((tonumber(state.last_hit_change) or 0) - 6.4511035007610351) / 6.7628708340282762
  f[106] = ((tonumber(state.team_gold_advantage) or 0) - 0) / 8523.386445494476
  f[107] = ((tonumber(state.team_experience_advantage) or 0) - 0) / 14047.310331784449
  f[108] = ((tonumber(state.kills_last_minute) or 0) - 0.12115677321156773) / 0.37695390682773522
  f[109] = ((tonumber(state.previous_fight) or 0) - 0.28614916286149161) / 0.45195997550132594
  f[110] = ((tonumber(state.previous_push) or 0) - 0.026978691019786911) / 0.16202111359525267
  f[111] = ((tonumber(state.previous_farm) or 0) - 0.76164383561643834) / 0.42607804834785634
  return f
end

local nodes = {
  [1] = { feature = 109, threshold = 0.47316321730613708, left = 2, right = 503 }, -- numeric__previous_fight
  [2] = { feature = 105, threshold = -0.58423465490341187, left = 3, right = 226 }, -- numeric__last_hit_change
  [3] = { feature = 102, threshold = -0.51181373000144958, left = 4, right = 141 }, -- numeric__last_hits
  [4] = { feature = 99, threshold = -1.4158540964126587, left = 5, right = 44 }, -- numeric__state_minute
  [5] = { feature = 105, threshold = -0.87996706366539001, left = 6, right = 33 }, -- numeric__last_hit_change
  [6] = { feature = 69, threshold = 0.5, left = 7, right = 32 }, -- categorical__hero_id_96
  [7] = { feature = 103, threshold = -1.1639747619628906, left = 8, right = 19 }, -- numeric__gold_change
  [8] = { feature = 5, threshold = 0.5, left = 9, right = 18 }, -- categorical__hero_id_9
  [9] = { feature = 88, threshold = 0.5, left = 10, right = 17 }, -- categorical__hero_id_123
  [10] = { feature = 106, threshold = -0.00052795916417380795, left = 11, right = 12 }, -- numeric__team_gold_advantage
  [11] = { label = "farm" },
  [12] = { feature = 106, threshold = 0.00011732425627997145, left = 13, right = 16 }, -- numeric__team_gold_advantage
  [13] = { feature = 97, threshold = 0.5, left = 14, right = 15 }, -- categorical__team_Dire
  [14] = { label = "unknown" },
  [15] = { label = "unknown" },
  [16] = { label = "farm" },
  [17] = { label = "unknown" },
  [18] = { label = "unknown" },
  [19] = { feature = 101, threshold = -1.0063060522079468, left = 20, right = 23 }, -- numeric__experience
  [20] = { feature = 106, threshold = -0.0039303626399487257, left = 21, right = 22 }, -- numeric__team_gold_advantage
  [21] = { label = "unknown" },
  [22] = { label = "unknown" },
  [23] = { feature = 107, threshold = -0.010962952859699726, left = 24, right = 25 }, -- numeric__team_experience_advantage
  [24] = { label = "unknown" },
  [25] = { feature = 103, threshold = -0.93335938453674316, left = 26, right = 31 }, -- numeric__gold_change
  [26] = { feature = 101, threshold = -1.0014147162437439, left = 27, right = 30 }, -- numeric__experience
  [27] = { feature = 104, threshold = -0.8645404577255249, left = 28, right = 29 }, -- numeric__experience_change
  [28] = { label = "unknown" },
  [29] = { label = "unknown" },
  [30] = { label = "unknown" },
  [31] = { label = "unknown" },
  [32] = { label = "farm" },
  [33] = { feature = 100, threshold = -1.0570173263549805, left = 34, right = 35 }, -- numeric__gold
  [34] = { label = "farm" },
  [35] = { feature = 105, threshold = -0.73210087418556213, left = 36, right = 43 }, -- numeric__last_hit_change
  [36] = { feature = 103, threshold = -0.70843818783760071, left = 37, right = 42 }, -- numeric__gold_change
  [37] = { feature = 101, threshold = -1.0050507783889771, left = 38, right = 39 }, -- numeric__experience
  [38] = { label = "farm" },
  [39] = { feature = 104, threshold = -0.83550414443016052, left = 40, right = 41 }, -- numeric__experience_change
  [40] = { label = "farm" },
  [41] = { label = "farm" },
  [42] = { label = "farm" },
  [43] = { label = "farm" },
  [44] = { feature = 105, threshold = -0.73210087418556213, left = 45, right = 104 }, -- numeric__last_hit_change
  [45] = { feature = 102, threshold = -0.77816459536552429, left = 46, right = 79 }, -- numeric__last_hits
  [46] = { feature = 106, threshold = -1.2274463772773743, left = 47, right = 48 }, -- numeric__team_gold_advantage
  [47] = { label = "unknown" },
  [48] = { feature = 102, threshold = -0.81145843863487244, left = 49, right = 70 }, -- numeric__last_hits
  [49] = { feature = 101, threshold = -0.99145874381065369, left = 50, right = 55 }, -- numeric__experience
  [50] = { feature = 100, threshold = -1.045363187789917, left = 51, right = 54 }, -- numeric__gold
  [51] = { feature = 98, threshold = 0.5, left = 52, right = 53 }, -- categorical__team_Radiant
  [52] = { label = "unknown" },
  [53] = { label = "unknown" },
  [54] = { label = "unknown" },
  [55] = { feature = 99, threshold = -1.2727218866348267, left = 56, right = 63 }, -- numeric__state_minute
  [56] = { feature = 107, threshold = -0.018081753514707088, left = 57, right = 60 }, -- numeric__team_experience_advantage
  [57] = { feature = 104, threshold = -0.69404521584510803, left = 58, right = 59 }, -- numeric__experience_change
  [58] = { label = "unknown" },
  [59] = { label = "unknown" },
  [60] = { feature = 102, threshold = -0.84475231170654297, left = 61, right = 62 }, -- numeric__last_hits
  [61] = { label = "unknown" },
  [62] = { label = "unknown" },
  [63] = { feature = 42, threshold = 0.5, left = 64, right = 67 }, -- categorical__hero_id_58
  [64] = { feature = 100, threshold = -1.0234761238098145, left = 65, right = 66 }, -- numeric__gold
  [65] = { label = "unknown" },
  [66] = { label = "unknown" },
  [67] = { feature = 106, threshold = -0.01325764087960124, left = 68, right = 69 }, -- numeric__team_gold_advantage
  [68] = { label = "unknown" },
  [69] = { label = "unknown" },
  [70] = { feature = 99, threshold = -0.98645749688148499, left = 71, right = 72 }, -- numeric__state_minute
  [71] = { label = "unknown" },
  [72] = { feature = 101, threshold = -0.85770297050476074, left = 73, right = 74 }, -- numeric__experience
  [73] = { label = "unknown" },
  [74] = { feature = 106, threshold = 0.83581802248954773, left = 75, right = 78 }, -- numeric__team_gold_advantage
  [75] = { feature = 100, threshold = -0.87811186909675598, left = 76, right = 77 }, -- numeric__gold
  [76] = { label = "unknown" },
  [77] = { label = "unknown" },
  [78] = { label = "unknown" },
  [79] = { feature = 99, threshold = -0.77175921201705933, left = 80, right = 85 }, -- numeric__state_minute
  [80] = { feature = 99, threshold = -0.91489142179489136, left = 81, right = 84 }, -- numeric__state_minute
  [81] = { feature = 104, threshold = -0.6560746431350708, left = 82, right = 83 }, -- numeric__experience_change
  [82] = { label = "farm" },
  [83] = { label = "farm" },
  [84] = { label = "farm" },
  [85] = { feature = 5, threshold = 0.5, left = 86, right = 97 }, -- categorical__hero_id_9
  [86] = { feature = 42, threshold = 0.5, left = 87, right = 96 }, -- categorical__hero_id_58
  [87] = { feature = 67, threshold = 0.5, left = 88, right = 95 }, -- categorical__hero_id_90
  [88] = { feature = 102, threshold = -0.57840144634246826, left = 89, right = 92 }, -- numeric__last_hits
  [89] = { feature = 99, threshold = 0.015467862598598003, left = 90, right = 91 }, -- numeric__state_minute
  [90] = { label = "unknown" },
  [91] = { label = "unknown" },
  [92] = { feature = 99, threshold = 0.15860006213188171, left = 93, right = 94 }, -- numeric__state_minute
  [93] = { label = "farm" },
  [94] = { label = "unknown" },
  [95] = { label = "unknown" },
  [96] = { label = "unknown" },
  [97] = { feature = 103, threshold = -0.72979143261909485, left = 98, right = 101 }, -- numeric__gold_change
  [98] = { feature = 99, threshold = -0.12766433134675026, left = 99, right = 100 }, -- numeric__state_minute
  [99] = { label = "farm" },
  [100] = { label = "unknown" },
  [101] = { feature = 107, threshold = -0.057555502280592918, left = 102, right = 103 }, -- numeric__team_experience_advantage
  [102] = { label = "unknown" },
  [103] = { label = "unknown" },
  [104] = { feature = 99, threshold = -0.84332531690597534, left = 105, right = 120 }, -- numeric__state_minute
  [105] = { feature = 102, threshold = -0.79814091324806213, left = 106, right = 115 }, -- numeric__last_hits
  [106] = { feature = 99, threshold = -1.3442879915237427, left = 107, right = 108 }, -- numeric__state_minute
  [107] = { label = "farm" },
  [108] = { feature = 99, threshold = -1.2011557817459106, left = 109, right = 112 }, -- numeric__state_minute
  [109] = { feature = 102, threshold = -0.83809351921081543, left = 110, right = 111 }, -- numeric__last_hits
  [110] = { label = "unknown" },
  [111] = { label = "unknown" },
  [112] = { feature = 104, threshold = -0.6910671591758728, left = 113, right = 114 }, -- numeric__experience_change
  [113] = { label = "unknown" },
  [114] = { label = "unknown" },
  [115] = { feature = 104, threshold = -0.55333083868026733, left = 116, right = 119 }, -- numeric__experience_change
  [116] = { feature = 102, threshold = -0.73155319690704346, left = 117, right = 118 }, -- numeric__last_hits
  [117] = { label = "farm" },
  [118] = { label = "farm" },
  [119] = { label = "farm" },
  [120] = { feature = 5, threshold = 0.5, left = 121, right = 138 }, -- categorical__hero_id_9
  [121] = { feature = 102, threshold = -0.75818827748298645, left = 122, right = 125 }, -- numeric__last_hits
  [122] = { feature = 106, threshold = 0.55247992277145386, left = 123, right = 124 }, -- numeric__team_gold_advantage
  [123] = { label = "unknown" },
  [124] = { label = "unknown" },
  [125] = { feature = 99, threshold = -0.056098234839737415, left = 126, right = 133 }, -- numeric__state_minute
  [126] = { feature = 102, threshold = -0.66496548056602478, left = 127, right = 132 }, -- numeric__last_hits
  [127] = { feature = 100, threshold = -0.69164544343948364, left = 128, right = 129 }, -- numeric__gold
  [128] = { label = "unknown" },
  [129] = { feature = 103, threshold = -0.70559108257293701, left = 130, right = 131 }, -- numeric__gold_change
  [130] = { label = "unknown" },
  [131] = { label = "unknown" },
  [132] = { label = "farm" },
  [133] = { feature = 104, threshold = -0.74318358302116394, left = 134, right = 135 }, -- numeric__experience_change
  [134] = { label = "unknown" },
  [135] = { feature = 106, threshold = 1.1879668235778809, left = 136, right = 137 }, -- numeric__team_gold_advantage
  [136] = { label = "unknown" },
  [137] = { label = "unknown" },
  [138] = { feature = 104, threshold = -0.60768082737922668, left = 139, right = 140 }, -- numeric__experience_change
  [139] = { label = "farm" },
  [140] = { label = "unknown" },
  [141] = { feature = 99, threshold = 0.73112887144088745, left = 142, right = 169 }, -- numeric__state_minute
  [142] = { feature = 42, threshold = 0.5, left = 143, right = 168 }, -- categorical__hero_id_58
  [143] = { feature = 99, threshold = 0.58799666166305542, left = 144, right = 163 }, -- numeric__state_minute
  [144] = { feature = 103, threshold = -0.060722071677446365, left = 145, right = 162 }, -- numeric__gold_change
  [145] = { feature = 104, threshold = -0.5950239896774292, left = 146, right = 153 }, -- numeric__experience_change
  [146] = { feature = 102, threshold = -0.4452260285615921, left = 147, right = 150 }, -- numeric__last_hits
  [147] = { feature = 100, threshold = -0.39216215908527374, left = 148, right = 149 }, -- numeric__gold
  [148] = { label = "farm" },
  [149] = { label = "farm" },
  [150] = { feature = 102, threshold = 0.73337650299072266, left = 151, right = 152 }, -- numeric__last_hits
  [151] = { label = "farm" },
  [152] = { label = "farm" },
  [153] = { feature = 100, threshold = 0.15615150332450867, left = 154, right = 161 }, -- numeric__gold
  [154] = { feature = 106, threshold = 0.63173246383666992, left = 155, right = 160 }, -- numeric__team_gold_advantage
  [155] = { feature = 99, threshold = 0.37329834699630737, left = 156, right = 159 }, -- numeric__state_minute
  [156] = { feature = 101, threshold = -0.38635455071926117, left = 157, right = 158 }, -- numeric__experience
  [157] = { label = "farm" },
  [158] = { label = "farm" },
  [159] = { label = "farm" },
  [160] = { label = "farm" },
  [161] = { label = "farm" },
  [162] = { label = "farm" },
  [163] = { feature = 102, threshold = -0.26210981607437134, left = 164, right = 165 }, -- numeric__last_hits
  [164] = { label = "unknown" },
  [165] = { feature = 103, threshold = -0.84936982393264771, left = 166, right = 167 }, -- numeric__gold_change
  [166] = { label = "farm" },
  [167] = { label = "farm" },
  [168] = { label = "farm" },
  [169] = { feature = 102, threshold = 0.33052083849906921, left = 170, right = 201 }, -- numeric__last_hits
  [170] = { feature = 102, threshold = -0.38529707491397858, left = 171, right = 178 }, -- numeric__last_hits
  [171] = { feature = 104, threshold = -0.81242400407791138, left = 172, right = 173 }, -- numeric__experience_change
  [172] = { label = "unknown" },
  [173] = { feature = 107, threshold = -0.95388367772102356, left = 174, right = 175 }, -- numeric__team_experience_advantage
  [174] = { label = "unknown" },
  [175] = { feature = 106, threshold = 0.79264268279075623, left = 176, right = 177 }, -- numeric__team_gold_advantage
  [176] = { label = "unknown" },
  [177] = { label = "unknown" },
  [178] = { feature = 99, threshold = 1.1605254411697388, left = 179, right = 184 }, -- numeric__state_minute
  [179] = { feature = 104, threshold = -0.72978222370147705, left = 180, right = 181 }, -- numeric__experience_change
  [180] = { label = "farm" },
  [181] = { feature = 102, threshold = -0.26210982352495193, left = 182, right = 183 }, -- numeric__last_hits
  [182] = { label = "unknown" },
  [183] = { label = "farm" },
  [184] = { feature = 106, threshold = 1.0614326000213623, left = 185, right = 196 }, -- numeric__team_gold_advantage
  [185] = { feature = 101, threshold = 1.2607028484344482, left = 186, right = 193 }, -- numeric__experience
  [186] = { feature = 103, threshold = -1.0244666934013367, left = 187, right = 188 }, -- numeric__gold_change
  [187] = { label = "unknown" },
  [188] = { feature = 106, threshold = -0.086233329027891159, left = 189, right = 192 }, -- numeric__team_gold_advantage
  [189] = { feature = 100, threshold = 0.41714766621589661, left = 190, right = 191 }, -- numeric__gold
  [190] = { label = "unknown" },
  [191] = { label = "unknown" },
  [192] = { label = "unknown" },
  [193] = { feature = 101, threshold = 1.7800994515419006, left = 194, right = 195 }, -- numeric__experience
  [194] = { label = "unknown" },
  [195] = { label = "unknown" },
  [196] = { feature = 99, threshold = 1.8046203255653381, left = 197, right = 200 }, -- numeric__state_minute
  [197] = { feature = 103, threshold = -0.55042392015457153, left = 198, right = 199 }, -- numeric__gold_change
  [198] = { label = "farm" },
  [199] = { label = "farm" },
  [200] = { label = "unknown" },
  [201] = { feature = 101, threshold = 1.9577911496162415, left = 202, right = 217 }, -- numeric__experience
  [202] = { feature = 104, threshold = -0.87421923875808716, left = 203, right = 206 }, -- numeric__experience_change
  [203] = { feature = 106, threshold = 0.32569213211536407, left = 204, right = 205 }, -- numeric__team_gold_advantage
  [204] = { label = "farm" },
  [205] = { label = "farm" },
  [206] = { feature = 101, threshold = 1.2838611602783203, left = 207, right = 214 }, -- numeric__experience
  [207] = { feature = 107, threshold = -1.9488784074783325, left = 208, right = 209 }, -- numeric__team_experience_advantage
  [208] = { label = "farm" },
  [209] = { feature = 105, threshold = -0.87996706366539001, left = 210, right = 211 }, -- numeric__last_hit_change
  [210] = { label = "farm" },
  [211] = { feature = 101, threshold = 1.0038397908210754, left = 212, right = 213 }, -- numeric__experience
  [212] = { label = "farm" },
  [213] = { label = "farm" },
  [214] = { feature = 104, threshold = -0.42229516804218292, left = 215, right = 216 }, -- numeric__experience_change
  [215] = { label = "farm" },
  [216] = { label = "fight" },
  [217] = { feature = 103, threshold = -0.57462430000305176, left = 218, right = 225 }, -- numeric__gold_change
  [218] = { feature = 106, threshold = 1.2888069748878479, left = 219, right = 224 }, -- numeric__team_gold_advantage
  [219] = { feature = 104, threshold = -0.94792675971984863, left = 220, right = 223 }, -- numeric__experience_change
  [220] = { feature = 99, threshold = 1.9477524757385254, left = 221, right = 222 }, -- numeric__state_minute
  [221] = { label = "farm" },
  [222] = { label = "farm" },
  [223] = { label = "farm" },
  [224] = { label = "fight" },
  [225] = { label = "unknown" },
  [226] = { feature = 107, threshold = 0.6895270049571991, left = 227, right = 416 }, -- numeric__team_experience_advantage
  [227] = { feature = 88, threshold = 0.5, left = 228, right = 401 }, -- categorical__hero_id_123
  [228] = { feature = 99, threshold = 1.1605254411697388, left = 229, right = 354 }, -- numeric__state_minute
  [229] = { feature = 105, threshold = -0.14063605666160583, left = 230, right = 291 }, -- numeric__last_hit_change
  [230] = { feature = 99, threshold = -0.77175921201705933, left = 231, right = 256 }, -- numeric__state_minute
  [231] = { feature = 103, threshold = -0.91912385821342468, left = 232, right = 233 }, -- numeric__gold_change
  [232] = { label = "unknown" },
  [233] = { feature = 99, threshold = -0.98645749688148499, left = 234, right = 247 }, -- numeric__state_minute
  [234] = { feature = 106, threshold = 0.086233332753181458, left = 235, right = 242 }, -- numeric__team_gold_advantage
  [235] = { feature = 103, threshold = -0.77961575984954834, left = 236, right = 239 }, -- numeric__gold_change
  [236] = { feature = 99, threshold = -1.2011557817459106, left = 237, right = 238 }, -- numeric__state_minute
  [237] = { label = "farm" },
  [238] = { label = "farm" },
  [239] = { feature = 107, threshold = -0.080727197229862213, left = 240, right = 241 }, -- numeric__team_experience_advantage
  [240] = { label = "farm" },
  [241] = { label = "farm" },
  [242] = { feature = 102, threshold = -0.77150583267211914, left = 243, right = 244 }, -- numeric__last_hits
  [243] = { label = "farm" },
  [244] = { feature = 107, threshold = 0.051468927413225174, left = 245, right = 246 }, -- numeric__team_experience_advantage
  [245] = { label = "farm" },
  [246] = { label = "farm" },
  [247] = { feature = 102, threshold = -0.79148215055465698, left = 248, right = 249 }, -- numeric__last_hits
  [248] = { label = "farm" },
  [249] = { feature = 102, threshold = -0.70824748277664185, left = 250, right = 253 }, -- numeric__last_hits
  [250] = { feature = 107, threshold = -0.039011025801301003, left = 251, right = 252 }, -- numeric__team_experience_advantage
  [251] = { label = "farm" },
  [252] = { label = "farm" },
  [253] = { feature = 100, threshold = -0.69261187314987183, left = 254, right = 255 }, -- numeric__gold
  [254] = { label = "farm" },
  [255] = { label = "farm" },
  [256] = { feature = 102, threshold = -0.55176636576652527, left = 257, right = 272 }, -- numeric__last_hits
  [257] = { feature = 5, threshold = 0.5, left = 258, right = 267 }, -- categorical__hero_id_9
  [258] = { feature = 42, threshold = 0.5, left = 259, right = 266 }, -- categorical__hero_id_58
  [259] = { feature = 102, threshold = -0.68494179844856262, left = 260, right = 263 }, -- numeric__last_hits
  [260] = { feature = 99, threshold = -0.55706092715263367, left = 261, right = 262 }, -- numeric__state_minute
  [261] = { label = "unknown" },
  [262] = { label = "unknown" },
  [263] = { feature = 99, threshold = 0.15860006213188171, left = 264, right = 265 }, -- numeric__state_minute
  [264] = { label = "farm" },
  [265] = { label = "unknown" },
  [266] = { label = "farm" },
  [267] = { feature = 101, threshold = -0.48413911461830139, left = 268, right = 271 }, -- numeric__experience
  [268] = { feature = 102, threshold = -0.73155319690704346, left = 269, right = 270 }, -- numeric__last_hits
  [269] = { label = "farm" },
  [270] = { label = "farm" },
  [271] = { label = "unknown" },
  [272] = { feature = 99, threshold = 0.73112887144088745, left = 273, right = 284 }, -- numeric__state_minute
  [273] = { feature = 102, threshold = -0.4718611091375351, left = 274, right = 279 }, -- numeric__last_hits
  [274] = { feature = 100, threshold = -0.31496050953865051, left = 275, right = 278 }, -- numeric__gold
  [275] = { feature = 106, threshold = 0.064117707312107086, left = 276, right = 277 }, -- numeric__team_gold_advantage
  [276] = { label = "farm" },
  [277] = { label = "farm" },
  [278] = { label = "farm" },
  [279] = { feature = 106, threshold = 0.58298423886299133, left = 280, right = 283 }, -- numeric__team_gold_advantage
  [280] = { feature = 107, threshold = 0.43599092960357666, left = 281, right = 282 }, -- numeric__team_experience_advantage
  [281] = { label = "farm" },
  [282] = { label = "farm" },
  [283] = { label = "farm" },
  [284] = { feature = 102, threshold = -0.25878043472766876, left = 285, right = 286 }, -- numeric__last_hits
  [285] = { label = "unknown" },
  [286] = { feature = 102, threshold = 0.70674142241477966, left = 287, right = 288 }, -- numeric__last_hits
  [287] = { label = "farm" },
  [288] = { feature = 106, threshold = -0.014020248781889677, left = 289, right = 290 }, -- numeric__team_gold_advantage
  [289] = { label = "farm" },
  [290] = { label = "farm" },
  [291] = { feature = 107, threshold = 0.061399655416607857, left = 292, right = 313 }, -- numeric__team_experience_advantage
  [292] = { feature = 80, threshold = 0.5, left = 293, right = 308 }, -- categorical__hero_id_109
  [293] = { feature = 63, threshold = 0.5, left = 294, right = 307 }, -- categorical__hero_id_86
  [294] = { feature = 99, threshold = 0.80269494652748108, left = 295, right = 302 }, -- numeric__state_minute
  [295] = { feature = 57, threshold = 0.5, left = 296, right = 299 }, -- categorical__hero_id_77
  [296] = { feature = 26, threshold = 0.5, left = 297, right = 298 }, -- categorical__hero_id_33
  [297] = { label = "farm" },
  [298] = { label = "farm" },
  [299] = { feature = 104, threshold = -0.26222323626279831, left = 300, right = 301 }, -- numeric__experience_change
  [300] = { label = "farm" },
  [301] = { label = "farm" },
  [302] = { feature = 102, threshold = -0.32869753241539001, left = 303, right = 304 }, -- numeric__last_hits
  [303] = { label = "unknown" },
  [304] = { feature = 106, threshold = -0.18683888018131256, left = 305, right = 306 }, -- numeric__team_gold_advantage
  [305] = { label = "farm" },
  [306] = { label = "farm" },
  [307] = { label = "farm" },
  [308] = { feature = 104, threshold = 0.37657548487186432, left = 309, right = 312 }, -- numeric__experience_change
  [309] = { feature = 104, threshold = -0.12820951640605927, left = 310, right = 311 }, -- numeric__experience_change
  [310] = { label = "farm" },
  [311] = { label = "farm" },
  [312] = { label = "push" },
  [313] = { feature = 101, threshold = -0.47781926393508911, left = 314, right = 331 }, -- numeric__experience
  [314] = { feature = 100, threshold = -0.71665924787521362, left = 315, right = 318 }, -- numeric__gold
  [315] = { feature = 104, threshold = 0.12269394472241402, left = 316, right = 317 }, -- numeric__experience_change
  [316] = { label = "farm" },
  [317] = { label = "farm" },
  [318] = { feature = 99, threshold = -0.77175921201705933, left = 319, right = 324 }, -- numeric__state_minute
  [319] = { feature = 103, threshold = -0.13332321494817734, left = 320, right = 321 }, -- numeric__gold_change
  [320] = { label = "farm" },
  [321] = { feature = 100, threshold = -0.61239719390869141, left = 322, right = 323 }, -- numeric__gold
  [322] = { label = "push" },
  [323] = { label = "push" },
  [324] = { feature = 106, threshold = 0.02651528175920248, left = 325, right = 328 }, -- numeric__team_gold_advantage
  [325] = { feature = 107, threshold = 0.11429234221577644, left = 326, right = 327 }, -- numeric__team_experience_advantage
  [326] = { label = "farm" },
  [327] = { label = "farm" },
  [328] = { feature = 103, threshold = -0.20734791457653046, left = 329, right = 330 }, -- numeric__gold_change
  [329] = { label = "farm" },
  [330] = { label = "farm" },
  [331] = { feature = 102, threshold = 0.9830804169178009, left = 332, right = 341 }, -- numeric__last_hits
  [332] = { feature = 102, threshold = -0.42524971067905426, left = 333, right = 336 }, -- numeric__last_hits
  [333] = { feature = 104, threshold = 0.019205573946237564, left = 334, right = 335 }, -- numeric__experience_change
  [334] = { label = "unknown" },
  [335] = { label = "farm" },
  [336] = { feature = 14, threshold = 0.5, left = 337, right = 340 }, -- categorical__hero_id_19
  [337] = { feature = 106, threshold = 0.57846724987030029, left = 338, right = 339 }, -- numeric__team_gold_advantage
  [338] = { label = "farm" },
  [339] = { label = "farm" },
  [340] = { label = "farm" },
  [341] = { feature = 103, threshold = 1.3656768798828125, left = 342, right = 349 }, -- numeric__gold_change
  [342] = { feature = 99, threshold = 0.65956276655197144, left = 343, right = 346 }, -- numeric__state_minute
  [343] = { feature = 107, threshold = 0.2348848283290863, left = 344, right = 345 }, -- numeric__team_experience_advantage
  [344] = { label = "farm" },
  [345] = { label = "farm" },
  [346] = { feature = 103, threshold = 0.76920866966247559, left = 347, right = 348 }, -- numeric__gold_change
  [347] = { label = "farm" },
  [348] = { label = "farm" },
  [349] = { feature = 105, threshold = 2.5209555625915527, left = 350, right = 353 }, -- numeric__last_hit_change
  [350] = { feature = 101, threshold = 1.0052250027656555, left = 351, right = 352 }, -- numeric__experience
  [351] = { label = "push" },
  [352] = { label = "push" },
  [353] = { label = "farm" },
  [354] = { feature = 102, threshold = -0.28541551530361176, left = 355, right = 358 }, -- numeric__last_hits
  [355] = { feature = 102, threshold = -0.4718611091375351, left = 356, right = 357 }, -- numeric__last_hits
  [356] = { label = "unknown" },
  [357] = { label = "unknown" },
  [358] = { feature = 102, threshold = 0.33052083849906921, left = 359, right = 368 }, -- numeric__last_hits
  [359] = { feature = 105, threshold = -0.14063605666160583, left = 360, right = 363 }, -- numeric__last_hit_change
  [360] = { feature = 99, threshold = 1.5899220705032349, left = 361, right = 362 }, -- numeric__state_minute
  [361] = { label = "farm" },
  [362] = { label = "unknown" },
  [363] = { feature = 107, threshold = -1.0320125222206116, left = 364, right = 365 }, -- numeric__team_experience_advantage
  [364] = { label = "farm" },
  [365] = { feature = 104, threshold = 0.26415287703275681, left = 366, right = 367 }, -- numeric__experience_change
  [366] = { label = "farm" },
  [367] = { label = "farm" },
  [368] = { feature = 100, threshold = 1.7819342017173767, left = 369, right = 382 }, -- numeric__gold
  [369] = { feature = 106, threshold = -0.10154414549469948, left = 370, right = 379 }, -- numeric__team_gold_advantage
  [370] = { feature = 106, threshold = -2.8507448434829712, left = 371, right = 372 }, -- numeric__team_gold_advantage
  [371] = { label = "farm" },
  [372] = { feature = 105, threshold = 1.0422935485839844, left = 373, right = 376 }, -- numeric__last_hit_change
  [373] = { feature = 99, threshold = 1.6614881753921509, left = 374, right = 375 }, -- numeric__state_minute
  [374] = { label = "farm" },
  [375] = { label = "farm" },
  [376] = { feature = 101, threshold = 1.4578735828399658, left = 377, right = 378 }, -- numeric__experience
  [377] = { label = "farm" },
  [378] = { label = "farm" },
  [379] = { feature = 105, threshold = 0.74656113982200623, left = 380, right = 381 }, -- numeric__last_hit_change
  [380] = { label = "farm" },
  [381] = { label = "fight" },
  [382] = { feature = 99, threshold = 2.5202813148498535, left = 383, right = 398 }, -- numeric__state_minute
  [383] = { feature = 99, threshold = 1.8046203255653381, left = 384, right = 391 }, -- numeric__state_minute
  [384] = { feature = 99, threshold = 1.6614881753921509, left = 385, right = 388 }, -- numeric__state_minute
  [385] = { feature = 106, threshold = -0.30140601098537445, left = 386, right = 387 }, -- numeric__team_gold_advantage
  [386] = { label = "farm" },
  [387] = { label = "farm" },
  [388] = { feature = 105, threshold = 1.3380259275436401, left = 389, right = 390 }, -- numeric__last_hit_change
  [389] = { label = "fight" },
  [390] = { label = "fight" },
  [391] = { feature = 99, threshold = 2.1624507904052734, left = 392, right = 395 }, -- numeric__state_minute
  [392] = { feature = 101, threshold = 3.1401662826538086, left = 393, right = 394 }, -- numeric__experience
  [393] = { label = "farm" },
  [394] = { label = "farm" },
  [395] = { feature = 106, threshold = -0.75756272673606873, left = 396, right = 397 }, -- numeric__team_gold_advantage
  [396] = { label = "fight" },
  [397] = { label = "farm" },
  [398] = { feature = 101, threshold = 4.2904226779937744, left = 399, right = 400 }, -- numeric__experience
  [399] = { label = "farm" },
  [400] = { label = "farm" },
  [401] = { feature = 101, threshold = -0.79710164666175842, left = 402, right = 403 }, -- numeric__experience
  [402] = { label = "farm" },
  [403] = { feature = 102, threshold = -0.70491811633110046, left = 404, right = 405 }, -- numeric__last_hits
  [404] = { label = "unknown" },
  [405] = { feature = 102, threshold = -0.24879227578639984, left = 406, right = 415 }, -- numeric__last_hits
  [406] = { feature = 99, threshold = 0.44486445188522339, left = 407, right = 412 }, -- numeric__state_minute
  [407] = { feature = 102, threshold = -0.55176636576652527, left = 408, right = 411 }, -- numeric__last_hits
  [408] = { feature = 103, threshold = -0.29703168570995331, left = 409, right = 410 }, -- numeric__gold_change
  [409] = { label = "farm" },
  [410] = { label = "unknown" },
  [411] = { label = "farm" },
  [412] = { feature = 102, threshold = -0.45188479125499725, left = 413, right = 414 }, -- numeric__last_hits
  [413] = { label = "unknown" },
  [414] = { label = "unknown" },
  [415] = { label = "farm" },
  [416] = { feature = 102, threshold = -0.3053918331861496, left = 417, right = 430 }, -- numeric__last_hits
  [417] = { feature = 99, threshold = 0.65956276655197144, left = 418, right = 425 }, -- numeric__state_minute
  [418] = { feature = 102, threshold = -0.64498916268348694, left = 419, right = 420 }, -- numeric__last_hits
  [419] = { label = "unknown" },
  [420] = { feature = 102, threshold = -0.49183742702007294, left = 421, right = 424 }, -- numeric__last_hits
  [421] = { feature = 105, threshold = -0.14063605666160583, left = 422, right = 423 }, -- numeric__last_hit_change
  [422] = { label = "unknown" },
  [423] = { label = "farm" },
  [424] = { label = "farm" },
  [425] = { feature = 106, threshold = 2.5351425409317017, left = 426, right = 429 }, -- numeric__team_gold_advantage
  [426] = { feature = 102, threshold = -0.43856725096702576, left = 427, right = 428 }, -- numeric__last_hits
  [427] = { label = "unknown" },
  [428] = { label = "unknown" },
  [429] = { label = "unknown" },
  [430] = { feature = 110, threshold = 2.9195041730999947, left = 431, right = 494 }, -- numeric__previous_push
  [431] = { feature = 42, threshold = 0.5, left = 432, right = 493 }, -- categorical__hero_id_58
  [432] = { feature = 100, threshold = 1.8297446370124817, left = 433, right = 468 }, -- numeric__gold
  [433] = { feature = 106, threshold = 1.1727733016014099, left = 434, right = 451 }, -- numeric__team_gold_advantage
  [434] = { feature = 106, threshold = 0.72019496560096741, left = 435, right = 442 }, -- numeric__team_gold_advantage
  [435] = { feature = 99, threshold = 1.0889593362808228, left = 436, right = 441 }, -- numeric__state_minute
  [436] = { feature = 104, threshold = 0.082489829510450363, left = 437, right = 438 }, -- numeric__experience_change
  [437] = { label = "farm" },
  [438] = { feature = 102, threshold = 1.1528791189193726, left = 439, right = 440 }, -- numeric__last_hits
  [439] = { label = "farm" },
  [440] = { label = "farm" },
  [441] = { label = "farm" },
  [442] = { feature = 103, threshold = 1.5179969668388367, left = 443, right = 448 }, -- numeric__gold_change
  [443] = { feature = 99, threshold = 1.3752237558364868, left = 444, right = 447 }, -- numeric__state_minute
  [444] = { feature = 107, threshold = 1.4868683218955994, left = 445, right = 446 }, -- numeric__team_experience_advantage
  [445] = { label = "farm" },
  [446] = { label = "farm" },
  [447] = { label = "farm" },
  [448] = { feature = 104, threshold = 1.1084392666816711, left = 449, right = 450 }, -- numeric__experience_change
  [449] = { label = "farm" },
  [450] = { label = "farm" },
  [451] = { feature = 103, threshold = 1.0496484041213989, left = 452, right = 461 }, -- numeric__gold_change
  [452] = { feature = 106, threshold = 1.2382401823997498, left = 453, right = 454 }, -- numeric__team_gold_advantage
  [453] = { label = "fight" },
  [454] = { feature = 100, threshold = 0.76381605863571167, left = 455, right = 458 }, -- numeric__gold
  [455] = { feature = 102, threshold = 0.16405155509710312, left = 456, right = 457 }, -- numeric__last_hits
  [456] = { label = "farm" },
  [457] = { label = "farm" },
  [458] = { feature = 102, threshold = 0.33052083849906921, left = 459, right = 460 }, -- numeric__last_hits
  [459] = { label = "farm" },
  [460] = { label = "farm" },
  [461] = { feature = 99, threshold = 1.0889593362808228, left = 462, right = 467 }, -- numeric__state_minute
  [462] = { feature = 106, threshold = 2.514434814453125, left = 463, right = 466 }, -- numeric__team_gold_advantage
  [463] = { feature = 104, threshold = 1.0235639214515686, left = 464, right = 465 }, -- numeric__experience_change
  [464] = { label = "farm" },
  [465] = { label = "push" },
  [466] = { label = "fight" },
  [467] = { label = "farm" },
  [468] = { feature = 99, threshold = 2.4487152099609375, left = 469, right = 492 }, -- numeric__state_minute
  [469] = { feature = 101, threshold = 2.0985161066055298, left = 470, right = 479 }, -- numeric__experience
  [470] = { feature = 103, threshold = 1.0425305962562561, left = 471, right = 474 }, -- numeric__gold_change
  [471] = { feature = 107, threshold = 1.6620975732803345, left = 472, right = 473 }, -- numeric__team_experience_advantage
  [472] = { label = "farm" },
  [473] = { label = "fight" },
  [474] = { feature = 105, threshold = 2.5209555625915527, left = 475, right = 478 }, -- numeric__last_hit_change
  [475] = { feature = 103, threshold = 1.6446930766105652, left = 476, right = 477 }, -- numeric__gold_change
  [476] = { label = "fight" },
  [477] = { label = "push" },
  [478] = { label = "farm" },
  [479] = { feature = 98, threshold = 0.5, left = 480, right = 487 }, -- categorical__team_Radiant
  [480] = { feature = 100, threshold = 2.7017025947570801, left = 481, right = 484 }, -- numeric__gold
  [481] = { feature = 101, threshold = 2.8281992673873901, left = 482, right = 483 }, -- numeric__experience
  [482] = { label = "farm" },
  [483] = { label = "farm" },
  [484] = { feature = 106, threshold = 2.2208309173583984, left = 485, right = 486 }, -- numeric__team_gold_advantage
  [485] = { label = "farm" },
  [486] = { label = "fight" },
  [487] = { feature = 99, threshold = 1.6614881753921509, left = 488, right = 489 }, -- numeric__state_minute
  [488] = { label = "fight" },
  [489] = { feature = 103, threshold = 0.85035115480422974, left = 490, right = 491 }, -- numeric__gold_change
  [490] = { label = "fight" },
  [491] = { label = "fight" },
  [492] = { label = "farm" },
  [493] = { label = "push" },
  [494] = { feature = 102, threshold = 0.88319885730743408, left = 495, right = 496 }, -- numeric__last_hits
  [495] = { label = "push" },
  [496] = { feature = 99, threshold = 1.0889593362808228, left = 497, right = 500 }, -- numeric__state_minute
  [497] = { feature = 101, threshold = 1.0891144871711731, left = 498, right = 499 }, -- numeric__experience
  [498] = { label = "push" },
  [499] = { label = "push" },
  [500] = { feature = 107, threshold = 1.6790758967399597, left = 501, right = 502 }, -- numeric__team_experience_advantage
  [501] = { label = "push" },
  [502] = { label = "farm" },
  [503] = { feature = 108, threshold = 1.0050120949745178, left = 504, right = 627 }, -- numeric__kills_last_minute
  [504] = { feature = 104, threshold = -0.93452537059783936, left = 505, right = 536 }, -- numeric__experience_change
  [505] = { feature = 102, threshold = -0.48184926807880402, left = 506, right = 519 }, -- numeric__last_hits
  [506] = { feature = 36, threshold = 0.5, left = 507, right = 518 }, -- categorical__hero_id_51
  [507] = { feature = 101, threshold = -0.11295601353049278, left = 508, right = 515 }, -- numeric__experience
  [508] = { feature = 102, threshold = -0.80479967594146729, left = 509, right = 510 }, -- numeric__last_hits
  [509] = { label = "unknown" },
  [510] = { feature = 103, threshold = -0.96467751264572144, left = 511, right = 512 }, -- numeric__gold_change
  [511] = { label = "fight" },
  [512] = { feature = 100, threshold = -0.37738126516342163, left = 513, right = 514 }, -- numeric__gold
  [513] = { label = "fight" },
  [514] = { label = "fight" },
  [515] = { feature = 106, threshold = -0.21018640697002411, left = 516, right = 517 }, -- numeric__team_gold_advantage
  [516] = { label = "unknown" },
  [517] = { label = "unknown" },
  [518] = { label = "unknown" },
  [519] = { feature = 99, threshold = 1.2320915460586548, left = 520, right = 529 }, -- numeric__state_minute
  [520] = { feature = 102, threshold = -0.022394046187400818, left = 521, right = 522 }, -- numeric__last_hits
  [521] = { label = "fight" },
  [522] = { feature = 103, threshold = -0.87214666604995728, left = 523, right = 528 }, -- numeric__gold_change
  [523] = { feature = 101, threshold = 0.70866808295249939, left = 524, right = 527 }, -- numeric__experience
  [524] = { feature = 101, threshold = 0.34947536885738373, left = 525, right = 526 }, -- numeric__experience
  [525] = { label = "farm" },
  [526] = { label = "fight" },
  [527] = { label = "farm" },
  [528] = { label = "fight" },
  [529] = { feature = 103, threshold = -0.46358725428581238, left = 530, right = 535 }, -- numeric__gold_change
  [530] = { feature = 101, threshold = 1.3669715523719788, left = 531, right = 532 }, -- numeric__experience
  [531] = { label = "fight" },
  [532] = { feature = 106, threshold = 0.61835750937461853, left = 533, right = 534 }, -- numeric__team_gold_advantage
  [533] = { label = "fight" },
  [534] = { label = "fight" },
  [535] = { label = "unknown" },
  [536] = { feature = 104, threshold = 3.1327910423278809, left = 537, right = 620 }, -- numeric__experience_change
  [537] = { feature = 105, threshold = -0.73210087418556213, left = 538, right = 581 }, -- numeric__last_hit_change
  [538] = { feature = 103, threshold = 0.13999874889850616, left = 539, right = 572 }, -- numeric__gold_change
  [539] = { feature = 102, threshold = -0.84475231170654297, left = 540, right = 545 }, -- numeric__last_hits
  [540] = { feature = 99, threshold = -1.0580235719680786, left = 541, right = 544 }, -- numeric__state_minute
  [541] = { feature = 99, threshold = -1.2011557817459106, left = 542, right = 543 }, -- numeric__state_minute
  [542] = { label = "fight" },
  [543] = { label = "fight" },
  [544] = { label = "fight" },
  [545] = { feature = 104, threshold = 0.6907632052898407, left = 546, right = 563 }, -- numeric__experience_change
  [546] = { feature = 107, threshold = -2.2898333072662354, left = 547, right = 550 }, -- numeric__team_experience_advantage
  [547] = { feature = 102, threshold = -0.5484369695186615, left = 548, right = 549 }, -- numeric__last_hits
  [548] = { label = "fight" },
  [549] = { label = "fight" },
  [550] = { feature = 102, threshold = -0.72489440441131592, left = 551, right = 556 }, -- numeric__last_hits
  [551] = { feature = 103, threshold = -0.27567841112613678, left = 552, right = 555 }, -- numeric__gold_change
  [552] = { feature = 106, threshold = -0.16026493161916733, left = 553, right = 554 }, -- numeric__team_gold_advantage
  [553] = { label = "fight" },
  [554] = { label = "fight" },
  [555] = { label = "fight" },
  [556] = { feature = 104, threshold = -0.88389796018600464, left = 557, right = 560 }, -- numeric__experience_change
  [557] = { feature = 99, threshold = 0.15860006213188171, left = 558, right = 559 }, -- numeric__state_minute
  [558] = { label = "fight" },
  [559] = { label = "fight" },
  [560] = { feature = 99, threshold = 0.87426102161407471, left = 561, right = 562 }, -- numeric__state_minute
  [561] = { label = "fight" },
  [562] = { label = "fight" },
  [563] = { feature = 102, threshold = -0.69160056114196777, left = 564, right = 565 }, -- numeric__last_hits
  [564] = { label = "fight" },
  [565] = { feature = 99, threshold = 1.0173932313919067, left = 566, right = 569 }, -- numeric__state_minute
  [566] = { feature = 101, threshold = 0.24489480257034302, left = 567, right = 568 }, -- numeric__experience
  [567] = { label = "fight" },
  [568] = { label = "fight" },
  [569] = { feature = 101, threshold = 0.83194845914840698, left = 570, right = 571 }, -- numeric__experience
  [570] = { label = "fight" },
  [571] = { label = "fight" },
  [572] = { feature = 102, threshold = -0.57174268364906311, left = 573, right = 576 }, -- numeric__last_hits
  [573] = { feature = 99, threshold = 0.58799666166305542, left = 574, right = 575 }, -- numeric__state_minute
  [574] = { label = "fight" },
  [575] = { label = "unknown" },
  [576] = { feature = 107, threshold = 1.4951972961425781, left = 577, right = 580 }, -- numeric__team_experience_advantage
  [577] = { feature = 97, threshold = 0.5, left = 578, right = 579 }, -- categorical__team_Dire
  [578] = { label = "fight" },
  [579] = { label = "fight" },
  [580] = { label = "fight" },
  [581] = { feature = 103, threshold = 1.7543066143989563, left = 582, right = 607 }, -- numeric__gold_change
  [582] = { feature = 39, threshold = 0.5, left = 583, right = 604 }, -- categorical__hero_id_55
  [583] = { feature = 99, threshold = -1.2011557817459106, left = 584, right = 589 }, -- numeric__state_minute
  [584] = { feature = 101, threshold = -0.94414645433425903, left = 585, right = 588 }, -- numeric__experience
  [585] = { feature = 104, threshold = -0.60544723272323608, left = 586, right = 587 }, -- numeric__experience_change
  [586] = { label = "fight" },
  [587] = { label = "fight" },
  [588] = { label = "fight" },
  [589] = { feature = 62, threshold = 0.5, left = 590, right = 603 }, -- categorical__hero_id_85
  [590] = { feature = 99, threshold = 1.0173932313919067, left = 591, right = 596 }, -- numeric__state_minute
  [591] = { feature = 107, threshold = 2.1421182155609131, left = 592, right = 595 }, -- numeric__team_experience_advantage
  [592] = { feature = 102, threshold = -0.68494179844856262, left = 593, right = 594 }, -- numeric__last_hits
  [593] = { label = "fight" },
  [594] = { label = "fight" },
  [595] = { label = "fight" },
  [596] = { feature = 102, threshold = -0.37197954952716827, left = 597, right = 600 }, -- numeric__last_hits
  [597] = { feature = 100, threshold = 0.33835421502590179, left = 598, right = 599 }, -- numeric__gold
  [598] = { label = "fight" },
  [599] = { label = "fight" },
  [600] = { feature = 105, threshold = -0.14063605666160583, left = 601, right = 602 }, -- numeric__last_hit_change
  [601] = { label = "fight" },
  [602] = { label = "fight" },
  [603] = { label = "fight" },
  [604] = { feature = 101, threshold = -0.023482488468289375, left = 605, right = 606 }, -- numeric__experience
  [605] = { label = "fight" },
  [606] = { label = "fight" },
  [607] = { feature = 107, threshold = 1.050841748714447, left = 608, right = 615 }, -- numeric__team_experience_advantage
  [608] = { feature = 104, threshold = 1.2223509550094604, left = 609, right = 612 }, -- numeric__experience_change
  [609] = { feature = 106, threshold = -0.45058383047580719, left = 610, right = 611 }, -- numeric__team_gold_advantage
  [610] = { label = "fight" },
  [611] = { label = "fight" },
  [612] = { feature = 101, threshold = 1.11595219373703, left = 613, right = 614 }, -- numeric__experience
  [613] = { label = "fight" },
  [614] = { label = "fight" },
  [615] = { feature = 101, threshold = 2.0728038549423218, left = 616, right = 619 }, -- numeric__experience
  [616] = { feature = 100, threshold = 1.3676716685295105, left = 617, right = 618 }, -- numeric__gold
  [617] = { label = "fight" },
  [618] = { label = "push" },
  [619] = { label = "fight" },
  [620] = { feature = 106, threshold = 1.1027306914329529, left = 621, right = 626 }, -- numeric__team_gold_advantage
  [621] = { feature = 100, threshold = 0.80349701642990112, left = 622, right = 623 }, -- numeric__gold
  [622] = { label = "fight" },
  [623] = { feature = 105, threshold = 0.45082874596118927, left = 624, right = 625 }, -- numeric__last_hit_change
  [624] = { label = "fight" },
  [625] = { label = "fight" },
  [626] = { label = "push" },
  [627] = { feature = 102, threshold = -0.71157687902450562, left = 628, right = 663 }, -- numeric__last_hits
  [628] = { feature = 105, threshold = -0.73210087418556213, left = 629, right = 654 }, -- numeric__last_hit_change
  [629] = { feature = 102, threshold = -0.80479967594146729, left = 630, right = 645 }, -- numeric__last_hits
  [630] = { feature = 99, threshold = -1.2011557817459106, left = 631, right = 634 }, -- numeric__state_minute
  [631] = { feature = 101, threshold = -0.99016016721725464, left = 632, right = 633 }, -- numeric__experience
  [632] = { label = "unknown" },
  [633] = { label = "unknown" },
  [634] = { feature = 101, threshold = -0.9038032591342926, left = 635, right = 636 }, -- numeric__experience
  [635] = { label = "unknown" },
  [636] = { feature = 103, threshold = -0.35966795682907104, left = 637, right = 640 }, -- numeric__gold_change
  [637] = { feature = 101, threshold = -0.85705369710922241, left = 638, right = 639 }, -- numeric__experience
  [638] = { label = "unknown" },
  [639] = { label = "unknown" },
  [640] = { feature = 103, threshold = -0.23439539968967438, left = 641, right = 642 }, -- numeric__gold_change
  [641] = { label = "unknown" },
  [642] = { feature = 107, threshold = 0.06737944670021534, left = 643, right = 644 }, -- numeric__team_experience_advantage
  [643] = { label = "unknown" },
  [644] = { label = "unknown" },
  [645] = { feature = 99, threshold = -0.62862700223922729, left = 646, right = 647 }, -- numeric__state_minute
  [646] = { label = "fight" },
  [647] = { feature = 103, threshold = -0.22870119661092758, left = 648, right = 649 }, -- numeric__gold_change
  [648] = { label = "fight" },
  [649] = { feature = 104, threshold = 0.062387772835791111, left = 650, right = 651 }, -- numeric__experience_change
  [650] = { label = "unknown" },
  [651] = { feature = 106, threshold = 0.20913049578666687, left = 652, right = 653 }, -- numeric__team_gold_advantage
  [652] = { label = "unknown" },
  [653] = { label = "unknown" },
  [654] = { feature = 99, threshold = -1.2011557817459106, left = 655, right = 658 }, -- numeric__state_minute
  [655] = { feature = 102, threshold = -0.82477599382400513, left = 656, right = 657 }, -- numeric__last_hits
  [656] = { label = "farm" },
  [657] = { label = "farm" },
  [658] = { feature = 99, threshold = -0.91489142179489136, left = 659, right = 660 }, -- numeric__state_minute
  [659] = { label = "fight" },
  [660] = { feature = 101, threshold = -0.74853402376174927, left = 661, right = 662 }, -- numeric__experience
  [661] = { label = "unknown" },
  [662] = { label = "fight" },
  [663] = { feature = 100, threshold = 0.51612266898155212, left = 664, right = 753 }, -- numeric__gold
  [664] = { feature = 108, threshold = 3.6578562259674072, left = 665, right = 744 }, -- numeric__kills_last_minute
  [665] = { feature = 105, threshold = -0.58423465490341187, left = 666, right = 685 }, -- numeric__last_hit_change
  [666] = { feature = 99, threshold = 0.58799666166305542, left = 667, right = 682 }, -- numeric__state_minute
  [667] = { feature = 102, threshold = -0.49849618971347809, left = 668, right = 675 }, -- numeric__last_hits
  [668] = { feature = 99, threshold = -0.59284397959709167, left = 669, right = 670 }, -- numeric__state_minute
  [669] = { label = "farm" },
  [670] = { feature = 99, threshold = -0.12766433134675026, left = 671, right = 672 }, -- numeric__state_minute
  [671] = { label = "fight" },
  [672] = { feature = 107, threshold = 0.14237601310014725, left = 673, right = 674 }, -- numeric__team_experience_advantage
  [673] = { label = "unknown" },
  [674] = { label = "fight" },
  [675] = { feature = 100, threshold = -0.44935277104377747, left = 676, right = 677 }, -- numeric__gold
  [676] = { label = "fight" },
  [677] = { feature = 103, threshold = -0.00093289255164563656, left = 678, right = 679 }, -- numeric__gold_change
  [678] = { label = "fight" },
  [679] = { feature = 102, threshold = 0.22398048639297485, left = 680, right = 681 }, -- numeric__last_hits
  [680] = { label = "fight" },
  [681] = { label = "fight" },
  [682] = { feature = 102, threshold = -0.47851987183094025, left = 683, right = 684 }, -- numeric__last_hits
  [683] = { label = "unknown" },
  [684] = { label = "fight" },
  [685] = { feature = 99, threshold = -0.48549483716487885, left = 686, right = 713 }, -- numeric__state_minute
  [686] = { feature = 106, threshold = -0.025518026202917099, left = 687, right = 696 }, -- numeric__team_gold_advantage
  [687] = { feature = 105, threshold = 0.0072301365435123444, left = 688, right = 691 }, -- numeric__last_hit_change
  [688] = { feature = 106, threshold = -0.17434384673833847, left = 689, right = 690 }, -- numeric__team_gold_advantage
  [689] = { label = "farm" },
  [690] = { label = "farm" },
  [691] = { feature = 107, threshold = -0.011354486923664808, left = 692, right = 695 }, -- numeric__team_experience_advantage
  [692] = { feature = 106, threshold = -0.14325291663408279, left = 693, right = 694 }, -- numeric__team_gold_advantage
  [693] = { label = "farm" },
  [694] = { label = "farm" },
  [695] = { label = "farm" },
  [696] = { feature = 106, threshold = 0.151934914290905, left = 697, right = 704 }, -- numeric__team_gold_advantage
  [697] = { feature = 105, threshold = 0.0072301365435123444, left = 698, right = 701 }, -- numeric__last_hit_change
  [698] = { feature = 103, threshold = 0.29801300168037415, left = 699, right = 700 }, -- numeric__gold_change
  [699] = { label = "fight" },
  [700] = { label = "fight" },
  [701] = { feature = 105, threshold = 0.3029625341296196, left = 702, right = 703 }, -- numeric__last_hit_change
  [702] = { label = "farm" },
  [703] = { label = "fight" },
  [704] = { feature = 101, threshold = -0.59607839584350586, left = 705, right = 710 }, -- numeric__experience
  [705] = { feature = 100, threshold = -0.67635291814804077, left = 706, right = 709 }, -- numeric__gold
  [706] = { feature = 101, threshold = -0.75225666165351868, left = 707, right = 708 }, -- numeric__experience
  [707] = { label = "farm" },
  [708] = { label = "farm" },
  [709] = { label = "push" },
  [710] = { feature = 103, threshold = 1.0140596032142639, left = 711, right = 712 }, -- numeric__gold_change
  [711] = { label = "farm" },
  [712] = { label = "farm" },
  [713] = { feature = 103, threshold = 1.8696142435073853, left = 714, right = 739 }, -- numeric__gold_change
  [714] = { feature = 107, threshold = 0.11998738348484039, left = 715, right = 726 }, -- numeric__team_experience_advantage
  [715] = { feature = 107, threshold = -0.034241430461406708, left = 716, right = 723 }, -- numeric__team_experience_advantage
  [716] = { feature = 106, threshold = -0.35672441124916077, left = 717, right = 720 }, -- numeric__team_gold_advantage
  [717] = { feature = 105, threshold = 0.0072301365435123444, left = 718, right = 719 }, -- numeric__last_hit_change
  [718] = { label = "fight" },
  [719] = { label = "farm" },
  [720] = { feature = 99, threshold = -0.19923043251037598, left = 721, right = 722 }, -- numeric__state_minute
  [721] = { label = "fight" },
  [722] = { label = "fight" },
  [723] = { feature = 107, threshold = 0.04022122360765934, left = 724, right = 725 }, -- numeric__team_experience_advantage
  [724] = { label = "farm" },
  [725] = { label = "fight" },
  [726] = { feature = 99, threshold = -0.19923043251037598, left = 727, right = 734 }, -- numeric__state_minute
  [727] = { feature = 99, threshold = -0.34236262738704681, left = 728, right = 731 }, -- numeric__state_minute
  [728] = { feature = 106, threshold = 0.42113542556762695, left = 729, right = 730 }, -- numeric__team_gold_advantage
  [729] = { label = "fight" },
  [730] = { label = "fight" },
  [731] = { feature = 101, threshold = -0.14018332213163376, left = 732, right = 733 }, -- numeric__experience
  [732] = { label = "fight" },
  [733] = { label = "fight" },
  [734] = { feature = 103, threshold = 0.44748593866825104, left = 735, right = 736 }, -- numeric__gold_change
  [735] = { label = "fight" },
  [736] = { feature = 107, threshold = 0.63592246174812317, left = 737, right = 738 }, -- numeric__team_experience_advantage
  [737] = { label = "farm" },
  [738] = { label = "fight" },
  [739] = { feature = 100, threshold = 0.33556859195232391, left = 740, right = 743 }, -- numeric__gold
  [740] = { feature = 102, threshold = 0.25394496321678162, left = 741, right = 742 }, -- numeric__last_hits
  [741] = { label = "farm" },
  [742] = { label = "farm" },
  [743] = { label = "farm" },
  [744] = { feature = 103, threshold = 2.5557663440704346, left = 745, right = 752 }, -- numeric__gold_change
  [745] = { feature = 103, threshold = 1.5009143352508545, left = 746, right = 751 }, -- numeric__gold_change
  [746] = { feature = 100, threshold = -0.30393169820308685, left = 747, right = 750 }, -- numeric__gold
  [747] = { feature = 100, threshold = -0.61546707153320312, left = 748, right = 749 }, -- numeric__gold
  [748] = { label = "fight" },
  [749] = { label = "fight" },
  [750] = { label = "fight" },
  [751] = { label = "fight" },
  [752] = { label = "fight" },
  [753] = { feature = 106, threshold = -0.06857602670788765, left = 754, right = 775 }, -- numeric__team_gold_advantage
  [754] = { feature = 103, threshold = 2.9073835611343384, left = 755, right = 772 }, -- numeric__gold_change
  [755] = { feature = 99, threshold = 1.1605254411697388, left = 756, right = 765 }, -- numeric__state_minute
  [756] = { feature = 99, threshold = 0.58799666166305542, left = 757, right = 760 }, -- numeric__state_minute
  [757] = { feature = 107, threshold = -0.53006589412689209, left = 758, right = 759 }, -- numeric__team_experience_advantage
  [758] = { label = "fight" },
  [759] = { label = "fight" },
  [760] = { feature = 105, threshold = 0.0072301365435123444, left = 761, right = 764 }, -- numeric__last_hit_change
  [761] = { feature = 100, threshold = 0.97779765725135803, left = 762, right = 763 }, -- numeric__gold
  [762] = { label = "fight" },
  [763] = { label = "fight" },
  [764] = { label = "farm" },
  [765] = { feature = 102, threshold = 1.4525238275527954, left = 766, right = 767 }, -- numeric__last_hits
  [766] = { label = "fight" },
  [767] = { feature = 102, threshold = 2.2648938894271851, left = 768, right = 771 }, -- numeric__last_hits
  [768] = { feature = 101, threshold = 1.8289700746536255, left = 769, right = 770 }, -- numeric__experience
  [769] = { label = "fight" },
  [770] = { label = "fight" },
  [771] = { label = "fight" },
  [772] = { feature = 105, threshold = 0.89442732930183411, left = 773, right = 774 }, -- numeric__last_hit_change
  [773] = { label = "fight" },
  [774] = { label = "farm" },
  [775] = { feature = 102, threshold = 0.87321069836616516, left = 776, right = 787 }, -- numeric__last_hits
  [776] = { feature = 107, threshold = 2.0516382455825806, left = 777, right = 786 }, -- numeric__team_experience_advantage
  [777] = { feature = 107, threshold = 0.57498553395271301, left = 778, right = 781 }, -- numeric__team_experience_advantage
  [778] = { feature = 103, threshold = 1.2873815298080444, left = 779, right = 780 }, -- numeric__gold_change
  [779] = { label = "fight" },
  [780] = { label = "fight" },
  [781] = { feature = 99, threshold = 0.30173225700855255, left = 782, right = 783 }, -- numeric__state_minute
  [782] = { label = "fight" },
  [783] = { feature = 104, threshold = 1.2536208033561707, left = 784, right = 785 }, -- numeric__experience_change
  [784] = { label = "fight" },
  [785] = { label = "fight" },
  [786] = { label = "farm" },
  [787] = { feature = 103, threshold = 1.3073112964630127, left = 788, right = 797 }, -- numeric__gold_change
  [788] = { feature = 99, threshold = 1.1605254411697388, left = 789, right = 796 }, -- numeric__state_minute
  [789] = { feature = 100, threshold = 1.4059314131736755, left = 790, right = 795 }, -- numeric__gold
  [790] = { feature = 104, threshold = 0.47112961113452911, left = 791, right = 792 }, -- numeric__experience_change
  [791] = { label = "fight" },
  [792] = { feature = 105, threshold = 0.15509633347392082, left = 793, right = 794 }, -- numeric__last_hit_change
  [793] = { label = "fight" },
  [794] = { label = "fight" },
  [795] = { label = "push" },
  [796] = { label = "fight" },
  [797] = { feature = 106, threshold = 2.8699860572814941, left = 798, right = 809 }, -- numeric__team_gold_advantage
  [798] = { feature = 28, threshold = 0.5, left = 799, right = 808 }, -- categorical__hero_id_36
  [799] = { feature = 102, threshold = 1.0063861608505249, left = 800, right = 801 }, -- numeric__last_hits
  [800] = { label = "fight" },
  [801] = { feature = 101, threshold = 1.8516089916229248, left = 802, right = 805 }, -- numeric__experience
  [802] = { feature = 102, threshold = 1.3393247127532959, left = 803, right = 804 }, -- numeric__last_hits
  [803] = { label = "push" },
  [804] = { label = "push" },
  [805] = { feature = 103, threshold = 3.0568565130233765, left = 806, right = 807 }, -- numeric__gold_change
  [806] = { label = "fight" },
  [807] = { label = "push" },
  [808] = { label = "fight" },
  [809] = { label = "fight" },
}

function M.predict_features(features)
  local index = 1
  while nodes[index].label == nil do
    local node = nodes[index]
    if features[node.feature] <= node.threshold then
      index = node.left
    else
      index = node.right
    end
  end
  return nodes[index].label
end

function M.predict(state)
  return M.predict_features(M.build_features(state))
end

return M
